/**
 * Smart Selector Generator - избегает авто-генерированные классы
 * @module utils/smart-selector-generator
 * @version 1.0.0
 */

/**
 * Проверяет похож ли класс на авто-генерированный
 */
function isAutoGeneratedClass(className: string): boolean {
  // Паттерны авто-генерации:
  // - el_12345, item_98765 (число в конце)
  // - hash123abc, xyz789 (хэш-подобные)
  // - col-sm-6-12345 (число после стандартного класса)
  // - class-a1b2c3d4 (буквы+цифры смешанные)
  
  const patterns = [
    /_\d+$/,                    // el_12345
    /^[a-z]{2,3}\d{3,}$/i,     // xyz789, hash123
    /-\d{4,}$/,                // col-sm-6-12345
    /^[a-f0-9]{6,}$/i,         // hash-подобные (6+ hex chars)
    /^[a-z]+\d+[a-z]+\d+/i     // mix123abc456
  ];
  
  return patterns.some(pattern => pattern.test(className));
}

/**
 * Фильтрует классы, оставляя только стабильные
 */
function getStableClasses(element: HTMLElement): string[] {
  return Array.from(element.classList)
    .filter(cls => !isAutoGeneratedClass(cls))
    .filter(cls => !cls.match(/^(hover|active|focus|disabled)/));
}

/**
 * Генерирует стабильный селектор без авто-генерированных классов
 */
export function generateSmartSelector(element: HTMLElement, mode: 'single' | 'array' = 'single'): string {
  if (mode === 'array') {
    return generateArraySelector(element);
  }

  // Приоритет 1: ID (если есть)
  if (element.id && !isAutoGeneratedClass(element.id)) {
    return `#${element.id}`;
  }

  // Приоритет 2: Стабильные классы
  const stableClasses = getStableClasses(element);
  if (stableClasses.length > 0) {
    const selector = `${element.tagName.toLowerCase()}.${stableClasses.join('.')}`;
    if (document.querySelectorAll(selector).length === 1) {
      return selector;
    }
  }

  // Приоритет 3: Структурный путь (без авто-генерированных классов)
  return generateStructuralPath(element);
}

/**
 * Генерирует селектор для массива элементов
 */
function generateArraySelector(element: HTMLElement): string {
  const parent = element.parentElement;
  if (!parent) return generateSmartSelector(element, 'single');

  // Находим все похожие элементы
  const siblings = Array.from(parent.children).filter((child): child is HTMLElement => {
    return child.tagName === element.tagName;
  });

  if (siblings.length > 1) {
    const stableClasses = getStableClasses(element);
    const tag = element.tagName.toLowerCase();
    
    // Селектор родителя
    let parentSelector = '';
    if (parent.id && !isAutoGeneratedClass(parent.id)) {
      parentSelector = `#${parent.id}`;
    } else {
      const parentStableClasses = getStableClasses(parent);
      if (parentStableClasses.length > 0) {
        parentSelector = `${parent.tagName.toLowerCase()}.${parentStableClasses[0]}`;
      } else {
        parentSelector = parent.tagName.toLowerCase();
      }
    }

    // Селектор элемента
    if (stableClasses.length > 0) {
      return `${parentSelector} > ${tag}.${stableClasses.join('.')}`;
    } else {
      return `${parentSelector} > ${tag}`;
    }
  }

  return generateSmartSelector(element, 'single');
}

/**
 * Генерирует структурный путь без авто-генерированных классов
 */
function generateStructuralPath(element: HTMLElement): string {
  const path: string[] = [];
  let current: HTMLElement | null = element;

  while (current && current !== document.body) {
    let selector = current.tagName.toLowerCase();

    // ID (если стабильный)
    if (current.id && !isAutoGeneratedClass(current.id)) {
      selector = `#${current.id}`;
      path.unshift(selector);
      break;
    }

    // Стабильные классы
    const stableClasses = getStableClasses(current);
    if (stableClasses.length > 0) {
      selector += `.${stableClasses[0]}`;
    }

    // Позиция среди siblings (только если нужно для однозначности)
    const parent = current.parentElement;
    if (parent && stableClasses.length === 0) {
      const siblings = Array.from(parent.children).filter(
        (child): child is Element => child.tagName === current!.tagName
      );
      if (siblings.length > 1) {
        const index = siblings.indexOf(current);
        selector += `:nth-of-type(${index + 1})`;
      }
    }

    path.unshift(selector);
    current = parent as HTMLElement | null;

    // Ограничение глубины
    if (path.length >= 5) break;
  }

  return path.join(' > ');
}

/**
 * Генерирует относительный селектор от контейнера до элемента
 */
export function generateRelativeSelector(container: HTMLElement, target: HTMLElement): string {
  // Если target не внутри container - возвращаем обычный селектор
  if (!container.contains(target)) {
    return generateSmartSelector(target, 'single');
  }

  const path: string[] = [];
  let current: HTMLElement | null = target;

  while (current && current !== container && current !== document.body) {
    let selector = current.tagName.toLowerCase();

    const stableClasses = getStableClasses(current);
    if (stableClasses.length > 0) {
      selector += `.${stableClasses[0]}`;
    }

    path.unshift(selector);
    current = current.parentElement;

    // Останавливаемся когда дошли до контейнера
    if (current === container) break;
  }

  return path.join(' > ');
}

/**
 * Объясняет что делает селектор
 */
export function explainSelector(selector: string): string {
  const parts = selector.split('>').map(s => s.trim());
  
  if (parts.length === 1) {
    return `Direct selector: ${selector}`;
  }
  
  return `Path: ${parts.length} levels deep`;
}
